name: CI Build App

on:
  push:
    branches: [master]
  pull_request:

env:
  IMAGE_REG: ghcr.io
  IMAGE_REPO: benc-uk/nodejs-demoapp

jobs:
  test:
    name: "Tests & Linting"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "NPM install"
        run: npm install --silent
        working-directory: ./src

      - name: "Run linting"
        run: npm run lint
        working-directory: ./src

      - name: "Run tests"
        run: npm run test-junit
        working-directory: ./src

      - name: "Upload test results"
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./src/test-results.xml

      - name: "Report on test results"
        uses: ashley-taylor/junit-report-annotations-action@master
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./src/test-results.xml
          name: Unit test results

  build:
    name: "Build & Push Image"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Docker build image"
        run: docker build . -t $IMAGE_REG/$IMAGE_REPO:dev-${{ github.run_id }}

      - name: "Login to GitHub container registry"
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REG }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: "Docker push image to ${{ env.IMAGE_REG }}"
        if: github.ref == 'refs/heads/master'
        run: docker push $IMAGE_REG/$IMAGE_REPO
