name: CI Build App

on:
  push:
    branches: [master]
  pull_request:

env:
  IMAGE_REG: ghcr.io
  IMAGE_REPO: benc-uk/nodejs-demoapp

jobs:
  test:
    name: "Tests & Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NPM install
        run: npm install --silent
        working-directory: ./src

      - name: Run linting
        run: npm run lint
        working-directory: ./src

      - name: Run tests
        run: npm run test-junit
        working-directory: ./src

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: test-results
      #     path: ./src/test-results.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: src/test-results.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: "Build & Push Image"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo ${{ github.ref }}

      - name: "Docker build image"
        run: docker build . -t $IMAGE_REG/$IMAGE_REPO:${{ github.run_id }} -t $IMAGE_REG/$IMAGE_REPO:latest

      - name: "Login to GitHub container registry"
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REG }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: "Docker push image to ${{ env.IMAGE_REG }}"
        if: github.ref == 'refs/heads/master'
        run: docker push $IMAGE_REG/$IMAGE_REPO
