name: Release Versioned Image

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  IMAGE_REG: ghcr.io
  IMAGE_NAME: nodejs-demoapp

jobs:
  releaseJob:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Docker build image"
        run: docker build . -t $IMAGE_REG/$IMAGE_REPO:latest $IMAGE_REG/$IMAGE_REPO:${{ github.event.release.tag_name }}

      - name: "Login to GitHub container registry"
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REG }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: "Docker push image to ${{ env.IMAGE_REG }}"
        if: github.ref == 'refs/heads/master'
        run: docker push $IMAGE_REG/$IMAGE_REPO
