name: 'Test Report'

on:
  workflow_run:
    workflows: ['CI Build App'] # runs after CI workflow
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results # artifact name
          name: Server Tests # Name of the check run which will be created
          path: 'test-results.json' # Path to test results (inside artifact .zip)
          reporter: mocha-json # Format of test results
